apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: shashankpodapp
  name: shashankpodapp
  namespace: shashank
spec:
  volumes: 
   - name: appvol
     emptyDir: {}
  containers:
  - image: nginx
    name: shashankpodapp
    ports:
    - containerPort: 80
    volumeMounts:
     - name: appvol
       mountPath: /usr/share/nginx/html/

  - image: alpine
    name: shashankc2 
    volumeMounts:
     - name: appvol
       mountPath: /covid
    command: ["/bin/sh","-c","while true; do cal 2020 >> /covid/index.html; sleep 20; done"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
