apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: shashankpod
  name: shashankpod
spec:
  containers:
  - image: alpine
    name: shashankpod
    command: ["/bin/sh","-c","ping fb.com"]
    
  - image: busybox
    name: sidecar
    command: ["/bin/sh","-c","sleep 10000"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
