apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: shashankpodapp
  name: shashankpodapp
  namespace: shashank
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: shashankpodapp
  type: NodePort
status:
  loadBalancer: {}
