apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: shashank
  name: shashank
  namespace: shashank
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: shashank
  type: NodePort
status:
  loadBalancer: {}
